name: Release project
on:
  release:
    types:
      - created
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        versions: [ 11 ]
    runs-on: ubuntu-latest
    name: Release with Java ${{ matrix.versions }} projects
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.versions }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.versions }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Deploy projects
        run: mvn --batch-mode clean verify
      - name: Deploy projects
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}